### PR TITLE
fix: client-side baseUrl is a path

### LINKED ISSUE #9279: V5 `signin()` throws error when using `redirect: false`
### Provider type

Email

### Environment

System:
OS: macOS 14.1.1
CPU: (8) arm64 Apple M1 Pro
Memory: 872.53 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
npm: 10.2.4 - ~/.nvm/versions/node/v18.18.2/bin/npm
bun: 1.0.14 - ~/.bun/bin/bun
Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
Browsers:
Chrome: 119.0.6045.199
Safari: 17.1

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

In `"next-auth": "5.0.0-beta.4"` the `signIn()` with `redirect: false` throws the following error on the client side:

```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid base URL
    at signIn (webpack-internal:///(:3000/en/auth/app-pages-browser)/../../node_modules/next-auth/react.js:172:19)
```

### How to reproduce

Install:
```
"next-auth": "5.0.0-beta.4"
```
Run:
```
const authResponse = await signIn("email", {
      email: data.email,
      redirect: false
})
```

### Expected behavior

Should not throw error

### PR DESCRIPTION
**Pull request by tills13**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Maintains the existing behaviour without using baseUrl which can be either a URL (server-side) or a path (client-side). Since baseUrl is used elsewhere in the function, and the aforementioned behaviour seems to work for the rest of the function body, it seemed easier to just skip trying to make a URL out of the response when what we really wanted was just a query parameter.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: https://github.com/nextauthjs/next-auth/issues/9279

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by tills13** [comment]
BTW: I just want to add that the dev setup process in this repo is mint. Clone to fix took like 15 minutes. Well done.

File: packages/next-auth/src/react.tsx [hunk 1]
```diff
@@ -276,7 +276,7 @@ export async function signIn<
     return
   }
 
-  const error = new URL(data.url, baseUrl).searchParams.get("error")
+  const error = new URLSearchParams(data.url?.split("?")[1]).get("error")
```
Comment (balazsorban44) [inline packages/next-auth/src/react.tsx:279]:
```suggestion
  const error = new URL(data.url).get("error")
```

`data.url` is supposed to always be there, but it's also supposed to be a valid URL, so we can drop `baseUrl`.

**Review by balazsorban44 — APPROVED** [review]

File: packages/next-auth/src/react.tsx (hunk 1 above)
Comment (tills13) [reply packages/next-auth/src/react.tsx]: Works for me thanks

**Comment by A7med3bdulBaset** [comment]
@balazsorban44 
This change hasn't been released yet. and makes an error in my codebase.

When will be the next `beta` release?

File: packages/next-auth/src/react.tsx (hunk 1 above)
Comment (A7med3bdulBaset) [reply packages/next-auth/src/react.tsx]: The suggested code will throw runtime `TypeError` since `data.url` is a relative url

```tsx
new URL("/login?error=CallbackRouteError").searchParams.get("error")
// Uncaught TypeError: Failed to construct 'URL': Invalid URL
```
```tsx
new URLSearchParams("/login?error=CallbackRouteError".split("?")[1]).get("error")
// "CallbackRouteError"

// or
new URL("/login?error=CallbackRouteError", window.location.origin).searchParams.get("error")
```

**Comment by remib18** [comment]
Hello,

I've identified that this PR might be linked to an issue with the credentials provider (mentioned in issue #9309). Could someone provide some insight into the rationale behind these changes? I'm interested in understanding more to potentially contribute to a solution.

**Comment by DevYemi** [comment]
> Hello,
> 
> I've identified that this PR might be linked to an issue with the credentials provider (mentioned in issue #9309). Could someone provide some insight into the rationale behind these changes? I'm interested in understanding more to potentially contribute to a solution.
> 
> Edit: After further inspection, it seems that the problem was solved by the latest commit.

The problem still persists
