### PR TITLE
Fix `signIn()` not respecting `{ redirect: true }`

### LINKED ISSUE #7670: signIn still redirects on SvelteKit eventhough redirect: false
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 111.0.1
    Safari: 16.4

### Reproduction URL

github.com/thomasmol/interview-processor

### Describe the issue

I am using the latest @auth/core and @auth/sveltekit packges to use the Email provider to sign in.

I don't want the page to redirect to another page when the `signIn` function is called so I provide the option of `redirect: false `. (I am trying to implement OTP instead of the magic link). However, the page still redirects to the verify-request page.

### How to reproduce

```javascript
const handleSignIn = async () => {
	loading = true;
	const response = await signIn('email', { redirect: false, email });
	loading = false;
};
```
use this code with the Email provider in any sveltekit project

### Expected behavior

For the page not to redirect and the response variable to not be `undefined`

### PR DESCRIPTION
**Pull request by sharknoon**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

SvelteKit: When specifying `{ redirect: false }` during `signIn()`, the site still redirects.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: [#7670](https://github.com/nextauthjs/next-auth/issues/7670)

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: packages/frameworks-sveltekit/src/lib/client.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export async function signIn<
   const data = await res.clone().json()
   const error = new URL(data.url).searchParams.get("error")
 
-  if (redirect || !isSupportingReturn || !error) {
+  if ((redirect && !error) || (!isSupportingReturn && !error)) {
```
Comment (balazsorban44) [inline packages/frameworks-sveltekit/src/lib/client.ts:66]:
```suggestion
  if (redirect || !isSupportingReturn) {
```

Copied from https://github.com/nextauthjs/next-auth/blob/a0f3b04c4328533841105820bcc025eb00340132/packages/next-auth/src/react/index.tsx#LL269C1-L269C41

No need to check `!error` on both sides of an "||".

**Review by balazsorban44 — APPROVED** [review]
