### PR TITLE
fix(ts): correct `credentials` types in `authorize` callback

### LINKED ISSUE #6641: How to augment Record type of credentials?
### Question 💬

I want to use Phone Number and Passwords as credentials for user Login. By default, credentials has this <code>Record<"email" | "password", string> | undefined</code>
So, both email and password are type of string. But, I want phone number to be of type number.  

I already have added phone number in credentials object.

<code>credentials: {
                 phoneNumber: {
          label: "Phone Number",
          type: "number",
        },
        password: {
          label: "Password",
          type: "password",
        },
      },</code>

 So, my credentials type is showing <code>Record<"phoneNumber" | "password", string> | undefined</code>. But, I want the phoneNumber to be of type number.

### How to reproduce ☕️

```ts
credentials: {
                 phoneNumber: {
          label: "Phone Number",
          type: "number",
        },
        password: {
          label: "Password",
          type: "password",
        },
      },
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

### PR DESCRIPTION
**Pull request by balazsorban44**
Closes #6641

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: packages/core/src/providers/credentials.ts [hunk 1]
```diff
@@ -40,8 +40,16 @@ export interface CredentialsConfig<
    * //...
    */
   authorize: (
-    /** See {@link CredentialInput} */
-    credentials: Record<keyof CredentialsInputs, string> | undefined,
+    /**
+     * The available keys are determined by {@link CredentialInput}.
+     *
+     * @note The existence/correctness of a field cannot be guaranteed at runtime,
```
Comment (ThangHuuVu) [inline packages/core/src/providers/credentials.ts:46]: Shouldn't it be
```suggestion
     * @note The existence/correctness of a field cannot be guaranteed at compile time,
```

**Comment by Soyeon1128** [comment]
When is the release scheduled?
