### PR TITLE
fix: OIDC provider `profile.id` field

### LINKED ISSUE #9992: [Auth0] OAuthAccountNotLinked: Another account already exists with the same e-mail address
### Provider type

Auth0

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700X 8-Core Processor
    Memory: 9.76 GB / 31.93 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/prisma-adapter: ^1.3.3 => 1.3.3 
    next: latest => 14.1.0 
    next-auth: beta => 5.0.0-beta.9 
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/pippinmole/auth0-authjs-bug

### Describe the issue

I haev a default setup with a prisma schema [defined here](https://github.com/pippinmole/auth0-authjs-bug/blob/main/prisma/schema.prisma), authjs config [defined here](https://github.com/pippinmole/auth0-authjs-bug/blob/main/auth.ts),

1. Log in using some custom credentials (this will insert a user into the database)
2. Log out
3. Log back in using the same credentials
4. Observe server logs

Please see attached video

https://github.com/nextauthjs/next-auth/assets/40035529/4ea89b4f-e502-4fee-b6ed-233625b8a369

As the error message says, I've taken a look at [this](https://errors.authjs.dev#oauthaccountnotlinked), and this is what it suggests:
> If you trust the OAuth provider to have verified the user's email address, you can enable automatic account linking by setting [allowDangerousEmailAccountLinking: true](https://authjs.dev/reference/core/providers#allowdangerousemailaccountlinking) in the provider configuration.

I shouldn't have to enable a dangerous flag just so a user can log in twice

### How to reproduce

1. Clone repo
2. Copy .env.example to .env
3. Enter relevant .env file variables for auth0
4. yarn run dev
5. Log in as the video above shows

### Expected behavior

It should let you log in the second time with no issues

### PR DESCRIPTION
**Pull request by ndom91**
## ☕️ Reasoning

- OIDC providers were still not getting the correct `profile.id`. They required an explicit default fallback for the `profile.id` value.

Fixes #9992

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Comment by ndom91** [comment]
@balazsorban44 @ThangHuuVu small fyi - playwright tests all passing in GHA now still. The vitest ones need fixed (decorator issue) and reenabled in another PR still though :pray:

File: packages/core/src/lib/utils/providers.ts [hunk 1]
```diff
@@ -86,14 +86,17 @@ function normalizeOAuth(
...
+ * and `account.id` are auto-generated UUID's.
+ *
+ * The result if this function is used to create the `User` in the database.
  * @see https://authjs.dev/reference/core/adapters#user
  * @see https://openid.net/specs/openid-connect-core-1_0.html#IDToken
  * @see https://openid.net/specs/openid-connect-core-1_0.html#
  */
 const defaultProfile: ProfileCallback<Profile> = (profile) => {
   return stripUndefined({
+    id: profile.sub ?? profile.id ?? crypto.randomUUID(),
```
Comment (yordis) [inline packages/core/src/lib/utils/providers.ts:99]: Thank you 🙇🏻‍♂️

**Review by ThangHuuVu — APPROVED** [review]
