### PR TITLE
fix(core): host detection/NEXTAUTH_URL

### LINKED ISSUE #5953: host detection/`NEXTAUTH_URL` breaks in some cases
### Provider type

Google

### Environment

  System:
    OS: Linux 6.0 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 20.61 GB / 31.06 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chromium: 108.0.5359.94
    Firefox: 107.0.1
  npmPackages:
    next: 13.0.2 => 13.0.2
    next-auth: ^4.18.0 => 4.18.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://next-auth-google-issue-repro.vercel.app/
https://github.com/mchataigner/next_auth_google_issue_repro

### Describe the issue

I have deployed on Vercel a simple app with next-auth and Google Oauth provider.
It works well locally but I get an error when trying to login in production.
It seems the error is coming from /api/auth/providers returning an empty object despite having multiple providers set in my configuration:
* Discord alone => works fine
* Google alone => error (empty providers object)
* Google + Discord => error (empty providers object)

I tried with next-auth 4.15.1 and 4.18.0 with no success
screenshot20221205_102909
Trying again this morning, and it worked a couple of times and then stopped working again.
It seems to work on cold start but not on hot ones.

### How to reproduce

Create simple app and add Google Oauth provider.

### Expected behavior

Adding Google provider should expose google login for the application or at least avoid crashing other providers.
screenshot20221205_101539

### PR DESCRIPTION
**Pull request by balazsorban44**
Follow-up of https://github.com/nextauthjs/next-auth/pull/5991#issuecomment-1343506610

Fixes #5953, closes #5980

### CODE REVIEW

File: packages/next-auth/src/next/index.ts [hunk 1]
```diff
@@ -139,19 +139,12 @@ export async function unstable_getServerSession<
...
+  const request = new Request("http://a/api/auth/session", {
+    headers: new Headers(req.headers),
+  })
 
   options.secret ??= process.env.NEXTAUTH_SECRET
-  const response = await AuthHandler(
-    new Request(urlOrError, { headers: req.headers }),
-    options
-  )
+  const response = await AuthHandler(request, options)
```
Comment (balazsorban44) [inline packages/next-auth/src/next/index.ts:147]: Since it's a get request, we don't really care about the host in this case.

(Internally, we just parse the session cookie anyway)

**Review by ThangHuuVu — APPROVED** [review]

**Comment by khuezy** [comment]
@ThangHuuVu @balazsorban44 did this change make it into the latest v4.18.8? I I downloaded
- https://github.com/nextauthjs/next-auth/releases/tag/next-auth%404.18.8
- https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.18.5

And compared the `packages/next-auth/src/core.ts` files. v4.18.8 had the older code (uses `host`). v4.18.5 (which the fix was introduced) uses `url`

**Comment by ThangHuuVu** [comment]
@khuezy we reverted this change in `next-auth`, see https://github.com/nextauthjs/next-auth/pull/6132

**Comment by khuezy** [comment]
Thanks for the response @ThangHuuVu ! v4.18.8 seems to be setting the redirect url in  `https://accounts.google.com/o/oauth2...../?redirect_uri` to localhost :(
