### PR TITLE
fix(providers): `signIn` action should allow custom id for the Credentials provider

### LINKED ISSUE #9673: next-auth v5 no longer works with multiple credentials providers
### Environment

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 829.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/1647_1705584306483/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/1647_1705584306483/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/1647_1705584306483/bin/npm
    pnpm: 8.14.0 - ~/Library/Caches/fnm_multishells/1647_1705584306483/bin/pnpm
    bun: 1.0.22 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.2.1
  npmPackages:
    next: 14.0.4 => 14.0.4 
    next-auth: 5.0.0-beta.5 => 5.0.0-beta.5 
    react: ^18 => 18.2.0 

### Reproduction URL

https://github.com/chungweileong94/nextauth-multi-credential-bug

### Describe the issue

According to the [documentation](https://authjs.dev/guides/providers/credentials#multiple-providers), we should able to create multiple credentials providers in Next Auth v5.

However, as soon as we add a second credentials provider, the server `signIn` function from `NextAuth(...)` will stop working. Even if I just add a unique `id` to the credentials provider, it will result the same issue too.

Also note that this was working fine in NextAuth v4

### How to reproduce

1. Create at least two credentials providers with unique ID.
2. Call the `signIn` function from `NextAuth(...)`, with the corresponding credential provider ID.

### Expected behavior

It should sign-in properly.

### PR DESCRIPTION
**Pull request by chungweileong94**
## ☕️ Reasoning

User should able to define multiple credential providers with unique id according to the [docs](https://authjs.dev/guides/providers/credentials#multiple-providers). However, it doesn't work with the `next-auth` v5  server `signIn`  function.

For example:

```ts
// auth.ts

export const { signIn } = NextAuth({
  providers: [
    CredentialsProvider({
      id: "password",
      // ...
    }),
    CredentialsProvider({
      id: "token",
      // ...
    }),
  ],
});
```

```ts
// actions.ts

import { signIn } from './auth.ts';

await signIn('password', formData); // In next-auth v5, this will do nothing.

```

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

- fix #9673

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: packages/next-auth/src/lib/actions.ts [hunk 1]
```diff
@@ -31,23 +32,28 @@ export async function signIn(
...
 
-  if (!foundProvider) {
+  if (!foundProviderId) {
     const url = `${base}?${new URLSearchParams({ callbackUrl })}`
     if (shouldRedirect) redirect(url)
     return url
   }
 
-  if (foundProvider === "credentials") {
+  if (foundProviderType === "credentials") {
```
Comment (chungweileong94) [inline packages/next-auth/src/lib/actions.ts:56]: Correct me if I'm wrong, but we should check the provider type instead of id.

**Review by balazsorban44 — APPROVED** [review]
Thank you! Good catch!
