### PR TITLE
fix(page): add character encoding and page titles

### LINKED ISSUE #1284: Add the character encoding of the signin page
**Describe the bug**
The sign in page did not have a character encoding.

**Steps to reproduce**
Just click a button with `signIn()` method on it.

**Expected behavior**
You'll see this error in your console. 
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Screenshots or error [logs**]
image

**Additional context**
Just add a
```html
<meta charset="utf-8" />
```
in the `<Head>` of the page and the error will go away.  
And also please add favicon too.  
Thank You and have a great day. 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

### PR DESCRIPTION
**Pull request by ExpressGradient**
**What**:
Fixed the character encoding for the sign in page

**Why**:
Every HTML document needs to have a UTF-8 character encoding.

**How**:
Just added a simple 
```html
<meta charset="utf-8">
```
in `src/server/pages/index.js`
Also added a missing title
```html
<title>Next Auth Sign in</title>
```

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged
      

Fixes #1284

### CODE REVIEW

File: src/server/pages/index.js [hunk 1]
```diff
@@ -10,7 +10,23 @@ export default function renderPage (req, res) {
 
   res.setHeader('Content-Type', 'text/html')
   function send (html) {
-    res.send(`<!DOCTYPE html><head><style type="text/css">${css()}</style><meta name="viewport" content="width=device-width, initial-scale=1"></head><body class="__next-auth-theme-${theme}"><div class="page">${html}</div></body></html>`)
+    res.send(`<!DOCTYPE html>
```
Comment (balazsorban44) [inline src/server/pages/index.js:13]: So obviously we could generate this smarter than an inline string... But for now - since it is such simple code - I think we can live with it. The reason it was on a simple line is (I guess) to make the sent html as small as possible. Could you remove the white spaces to reflect the code that was here before?

File: src/server/pages/index.js [hunk 2]
```diff
@@ -10,7 +10,23 @@ export default function renderPage (req, res) {
...
+      <html lang="en">
+      <head>
+          <meta charset="UTF-8">
+          <meta http-equiv="X-UA-Compatible" content="IE=edge">
+          <meta name="viewport" content="width=device-width, initial-scale=1.0">
+          <style>
+              ${css()}
+          </style>
+          <title>Next Auth Sign in</title>
```
Comment (balazsorban44) [inline src/server/pages/index.js:22]: This one is probably a good idea to add, but if you check the lines 33-36 in this file, you can see that simply setting `Next Auth Sign in` is not sufficient. I think a nice way of setting a custom title for each of the page types would be if the `send` function took a `title` param in addition to html, and add individual titles for `signin`, `signout`, `verifyRequest` and `error`.

I would also prefer if the function signature becomes: `function send({html, title})` to future proof us. #1154 would require us to send `locale` or something similar here.

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks so much! Only some small change requests. :slightly_smiling_face:

Also note that linting has failed! Try running `npm run lint --fix` before commiting.

File: src/server/pages/index.js (hunk 1 above)
Comment (ExpressGradient) [reply src/server/pages/index.js:13]: Sure. I just thought it would be more readable if its multi-line.  
But as you wish.

File: src/server/pages/index.js (hunk 2 above)
Comment (ExpressGradient) [reply src/server/pages/index.js:22]: Ok, so should I change the function's signature to `function send({ html, title })`?

File: src/server/pages/index.js (hunk 1 above)
Comment (balazsorban44) [reply src/server/pages/index.js:13]: It is certainly, and we should maybe create a new .html file so we get syntax highlighting and so on, but this could be a different PR. Than we should also minify that file and inject variables into it. It's just more work not indeed for this PR, but ideas are welcome! :)

File: src/server/pages/index.js (hunk 2 above)
Comment (balazsorban44) [reply src/server/pages/index.js:22]: yes. Usually I have a rule of thumb, if you need more than one param I just like to name them for convinience.

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Sorry if I explained myself poorly, my thoughts were that you also update this section:
https://github.com/nextauthjs/next-auth/blob/d8d497cc91a73adcc0eec2b1479a342f0b97f440/src/server/pages/index.js#L17-L20

So it becomes something like this. (Please run the linter before commiting)
```diff
- signin (props) { send(signin({ csrfToken, providers, callbackUrl, ...req.query, ...props })) },
+ signin (props) { send({
+   html: signin({ csrfToken, providers, callbackUrl, ...req.query, ...props }),
+   title: "Sign in
+ }) },
- signout (props) { send(signout({ csrfToken, baseUrl, basePath, ...props })) },
+ signout (props) { send({
+   html: signout({ csrfToken, baseUrl, basePath, ...props }),
+   title: "Sign out
+ }) },
- verifyRequest (props) { send(verifyRequest({ baseUrl, ...props })) },
+ verifyRequest (props) { send({
+   html: verifyRequest({ baseUrl, ...props }),
+   title: "Verify request"
+ }) },
- error (props) { send(error({ basePath, baseUrl, res, ...props })) }
+ error (props) { send({
+   html: error({ basePath, baseUrl, res, ...props }),
+   title: "Error
+ }) }
```

**Comment by huynhminhcanh** [comment]
31410003781426

**Comment by ExpressGradient** [comment]
> 
> 
> Sorry if I explained myself poorly, my thoughts were that you also update this section:
> 
> https://github.com/nextauthjs/next-auth/blob/d8d497cc91a73adcc0eec2b1479a342f0b97f440/src/server/pages/index.js#L17-L20
> 
> So it becomes something like this. (Please run the linter before commiting)
> 
> ```diff
> - signin (props) { send(signin({ csrfToken, providers, callbackUrl, ...req.query, ...props })) },
> + signin (props) { send({
> +   html: signin({ csrfToken, providers, callbackUrl, ...req.query, ...props }),
> +   title: "Sign in
> + }) },
> - signout (props) { send(signout({ csrfToken, baseUrl, basePath, ...props })) },
> + signout (props) { send({
> +   html: signout({ csrfToken, baseUrl, basePath, ...props }),
> +   title: "Sign out
> + }) },
> - verifyRequest (props) { send(verifyRequest({ baseUrl, ...props })) },
> + verifyRequest (props) { send({
> +   html: verifyRequest({ baseUrl, ...props }),
> +   title: "Verify request"
> + }) },
> - error (props) { send(error({ basePath, baseUrl, res, ...props })) }
> + error (props) { send({
> +   html: error({ basePath, baseUrl, res, ...props }),
> +   title: "Error
> + }) }
> ```

No no, you explained it right, it's my dumb brain couldn't interpret it.  
Anyways, is there anything else more?

**Review by balazsorban44 — APPROVED** [review]
LGTM! Thanks :slightly_smiling_face:
