### PR TITLE
fix(providers): refactor FusionAuth to v4

### LINKED ISSUE #3357: FusionAuth Provider not working [CALLBACK_OAUTH_ERROR]
### Description 🐜

I am using FusionAuth for Identity and Access Management, but I have trouble integrating with NextAuth.

I followed the [document](https://next-auth.js.org/providers/fusionauth#configuration) to try to get the first successful run, but it failed immediately.

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Create a new application and let everything in default settings but the redirect URL must be `http://localhost:3000/api/auth/callback/fusionauth`. Notice that it's `http` without the `s`, because my localhost does not have SSL.
2. Follow this [document](https://next-auth.js.org/providers/fusionauth#configuration) using the application clientId and secret. Set the issuer to `http://localhost:9011/`. The last `/` is a must, without it, NextAuth will throw `invalid_URL` error.
3. Add `<button onClick={() => signIn()}>Sign In</button>` to the page
4. Run the app, then click the `Sign In` button
5. Get the error `[next-auth][error][CALLBACK_OAUTH_ERROR]`

### Screenshots / Logs 📽

Application Settings

Error

### Environment 🖥

  System:
    OS: Linux 5.15 Fedora Linux 35 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.72 GB / 15.35 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.1.0/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v17.1.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0
  npmPackages:
    next: 12.0.5 => 12.0.5 
    next-auth: ^4.0.2 => 4.0.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

### PR DESCRIPTION
**Pull request by alessandrojcm**
## Reasoning 💡

The FusionAuth provider was missing typings and some provider-specific configuration on NextAuth v4.

## Checklist 🧢

- [x] Documentation
- [x] Tests
- [ ] Ready to be merged

## Affected issues 🎟
Fixes #3357

### CODE REVIEW

**Comment by alessandrojcm** [comment]
Docs are missing, will do them shortly. Also not sure if/how tests could be written for this. For reference here is an image of the provider working on my machine
Screenshot 2021-12-06 at 15-15-04 https localhost

**Comment by alessandrojcm** [comment]
Docs done, see https://github.com/nextauthjs/docs/pull/161

File: src/providers/fusionauth.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
+import { OAuthConfig, OAuthUserConfig } from "./oauth"
+
+// This is the default openid signature returned from FusionAuth
+// it can be customized using lambda functions https://fusionauth.io/docs/v1/tech/lambdas/
+export interface FusionAuthProfile {
```
Comment (balazsorban44) [inline src/providers/fusionauth.ts:5]:
```suggestion
/** This is the default openid signature returned from FusionAuth
 * it can be customized using [lambda functions](https://fusionauth.io/docs/v1/tech/lambdas)
 */
export interface FusionAuthProfile {
```

File: src/providers/fusionauth.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+  // tenantId only needed if there is more than one tenant configured on the server
+  options: OAuthUserConfig<P> & { tenantId?: string }
+): OAuthConfig<P> {
+  return {
+    id: "fusionauth",
+    name: "FusionAuth",
+    type: "oauth",
+    wellKnown: !options?.tenantId
+      ? `${options.issuer}/.well-known/openid-configuration`
+      : `${options.issuer}/.well-known/openid-configuration?tenantId=${options.tenantId}`,
```
Comment (balazsorban44) [inline src/providers/fusionauth.ts:34]:
```suggestion
    wellKnown: options?.tenantId
      ? `${options.issuer}/.well-known/openid-configuration?tenantId=${options.tenantId}`
      : `${options.issuer}/.well-known/openid-configuration`,
```

File: src/providers/fusionauth.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    jwks_endpoint: `${options.issuer}/.well-known/jwks.json`,
```
Comment (balazsorban44) [inline src/providers/fusionauth.ts:35]: I wonder if this might be unnecessary/extracted from the `openid-configuration` endpoint? :thinking:

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thank you, also for converting to TS! :pray: just a few comments.

Regarding testing, we don't have a good idea yet for testing, mostly done manually. Thank you for the image above!

File: src/providers/fusionauth.ts (hunk 3 above)
Comment (alessandrojcm) [reply src/providers/fusionauth.ts:36]: I think so yes, the response payload from the [docs](https://fusionauth.io/docs/v1/tech/oauth/endpoints/#openid-configuration) returns it, but don't know how could we use that?

Comment (balazsorban44) [reply src/providers/fusionauth.ts:36]: just remove it, I believe `openid-client` will take care of the rest.😉 do test locally though, please.

Comment (alessandrojcm) [reply src/providers/fusionauth.ts]: So it works, but for some reason the `iframe` in `api-example` is returning `null`; but the call to `/api/session` works correctly (see image
Screenshot_20211207_113618
).

Comment (alessandrojcm) [reply src/providers/fusionauth.ts]: Ah never mind, I'm using a self-signed certificate to fake SSL so that was interfering with it; setting `NODE_TLS_REJECT_UNAUTHORIZED` to `0` makes it work. You think this is good to go now? @balazsorban44 
Screenshot 2021-12-08 at 12-55-23 https localhost
.

**Review by balazsorban44 — APPROVED** [review]
