### PR TITLE
Use relative URL for Signin page callbackUrl

### LINKED ISSUE #4483: Incorrect `callbackUrl` appended when securing page with middleware withAuth
### Environment

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
    Memory: 10.76 GB / 23.74 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.56)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    next: 12.1.5 => 12.1.5 
    next-auth: ^4.3.3 => 4.3.3 
    react: 18.0.0 => 18.0.0 
```

### Reproduction URL

https://github.com/vercel/next.js/issues/36334 (related issue in nextjs middleware)

### Describe the issue

When middleware `withAuth` redirect user to signin page, `req.url` is appended to params as `callbackUrl`. This url is composed by set next server hostname, port, pathname and hard-coded protocol http (see [related issue in nextjs repo](https://github.com/vercel/next.js/issues/36334)).   
This is not always the url on client end (ex: next server is behind ssl proxy or load balancer).  Hence `callbackUrl` is not working as intended.
https://github.com/nextauthjs/next-auth/blob/c6903d3e857f4a0875ffe49fc634a36346bdde88/packages/next-auth/src/next/middleware.ts#L92-L95

### How to reproduce

See [related issue in nextjs repo](https://github.com/vercel/next.js/issues/36334)

### Expected behavior

Suggestion to use `req.nextUrl.pathname` as callbackUrl instead of `req.url`.   
Or reconstruct full url using NEXTAUTH_URL and `req.url`.  
Or add another callback to override default behavior when user is not authorized.

### PR DESCRIPTION
**Pull request by bboyz269**
## ☕️ Reasoning

As of now, there's no way to determine actual address (protocol, host, port) which end-user access next app within middleware functions. Sign in page 's `callbackUrl` does not behave as expected when next app is behind ssl proxy or load balancer.  

As a simple fix, using relative URL for `callbackUrl` would restore the expected behavior.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/4483

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: apps/dev/components/header.js [hunk 1]
```diff
@@ -108,6 +108,11 @@ export default function Header() {
               <a>Middleware protected</a>
             </Link>
           </li>
+          <li className={styles.navItem}>
```
Comment (ThangHuuVu) [inline apps/dev/components/header.js:111]: Is this just for testing? If so, I don't think we need it here, as we can just append the param to the URL `/middleware-protected` manually. Please remove 🙏

**Review by ThangHuuVu — CHANGES_REQUESTED** [review]

File: apps/dev/components/header.js (hunk 1 above)
Comment (bboyz269) [reply apps/dev/components/header.js]: Sure.

File: apps/dev/components/header.js [hunk 2]
```diff
@@ -104,7 +104,7 @@ export default function Header() {
             </Link>
           </li>
           <li className={styles.navItem}>
-            <Link href="/middleware-protected">
+            <Link href="/middleware-protected?with-params">
```
Comment (ThangHuuVu) [inline apps/dev/components/header.js:107]:
```suggestion
            <Link href="/middleware-protected">
```

**Review by ThangHuuVu — APPROVED** [review]
LGTM! @ndom91 @balazsorban44 do you have any concerns?

**Review by balazsorban44 — APPROVED** [review]
Thanks!
