### PR TITLE
Fix redirect for protected pages

### LINKED ISSUE #9144: Invalid redirect URL on protected pages using authorized callback and middleware in next-auth v5 beta
### Environment

- System
  -  OS: Ubuntu 20.04.6 LTS (Focal Fossa)
  -  Node.js: 18.15.0
- Browser
  -  Firefox: 119.0.1
- npmPackages
  -  next: latest => 14.0.2
  -  next-auth: beta => 5.0.0-beta.3
  -  react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

When creating protected pages using middleware and authorized() callback in next-auth v5 (beta) and Next.js 14 (App Router), the page gets redirected to an invalid URL (`http://localhost:3010/%7D/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3010%2F%257D%2Fsignin`) and shows a 404 error page.
screenshot1

#### Root Cause
The extra brace `}` (`%7D`) in the redirected URL seems to be caused by a bug (typo?) in the source code. 
https://github.com/nextauthjs/next-auth/blob/465e882176de5c9e1bc5a482c429ba8d54c55e22/packages/next-auth/src/lib/index.ts#L193-L194
There are two braces `}}` instead of single `}`.
Fixing it would remove the extra `}` from the URL, but the resulting URL (/signin) is non-existent page unless it's created manually.

updated:
Above problem has already been fixed in #9145 but it still redirect to /signin instead of the builtin sign-in page (`/api/auth/signin`) and isn't working.

### How to reproduce

1. Create a protected page by adding authorized() callback to the next-auth's config.
2. When accessing the protected page without logging in, it redirects to an invalid URL (/}/signin?...) and shows a 404 error.

This can be reproduced in the [official next-auth's example app](https://github.com/nextauthjs/next-auth-example) (Reproduction URL) without modification.
So this happens in the official live demo page [Middleware Example](https://next-auth-example.vercel.app/middleware-example).
screenshot2

### Expected behavior

The browser should be redirected to the builtin sign-in page (`/api/auth/signin`) when accessing protected page.

### PR DESCRIPTION
**Pull request by pinelibg**
> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

This PR fixes several issues related to redirect behavior for middleware protected pages:

1. Incorrect default redirect URL
   - Unauthorized users were redirected to `/signin` when accessing protected pages.  
   - This PR changes the default redirect URL to `/api/auth/signin` (built-in sign-in page) instead.
   
2. Invalid redirect URL when `AUTH_URL` is set
   - The `reqWithEnvUrl` function, which overrides request when `AUTH_URL` is set, used Web API's `URL` instead of `NextURL` for `nextUrl` property, breaking the redirect URL.
   - This PR uses `NextURL` for `nextUrl` property.
   
3. Not redirect back to original protected page after login
   - The callback URL was set to the signin page itself.
   - This PR fixes the callback URL parameter to redirect back to the original requested page.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: #9144 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: packages/next-auth/src/lib/env.ts [hunk 1]
```diff
@@ -43,11 +43,12 @@ export function detectOrigin(h: Headers | ReturnType<typeof headers>) {
 export function reqWithEnvUrl(req: NextRequest): NextRequest {
   const url = process.env.AUTH_URL ?? process.env.NEXTAUTH_URL
   if (!url) return req
-  const nonBase = req.nextUrl.href.replace(req.nextUrl.origin, "")
+  // const nonBase = req.nextUrl.href.replace(req.nextUrl.origin, "")
```
Comment (balazsorban44) [inline packages/next-auth/src/lib/env.ts:46]:
```suggestion
```

**Comment by pinelibg** [comment]
Thanks!

**Comment by evanrs** [comment]
@balazsorban44 do foresee reintroducing `basePath`?
