### PR TITLE
fix(next): conditional RSC support

### LINKED ISSUE #5743: Getting "Error: Cannot find module 'next/headers'" when accessing "api/auth/signin"
### Question 💬

Hello I am trying to implement Facebook Login but I am getting this error:

`error - Error: Cannot find module 'next/headers'
Require stack:
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next-auth/next/index.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next-auth/index.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/.next/server/pages/api/auth/[...nextauth].js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/next-server.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/next.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/lib/start-server.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/cli/next-dev.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/lib/commands.js
- /Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.mod._resolveFilename (/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next-auth/next/index.js:15:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next-auth/next/index.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next-auth/index.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/.next/server/pages/api/auth/[...nextauth].js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/next-server.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/next.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/server/lib/start-server.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/cli/next-dev.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/lib/commands.js',
    '/Users/edgarlcs/Documents/GitHub/rifadisimo/rifadisimo/node_modules/next/dist/bin/next'
  ]
}`

### How to reproduce ☕️

Here is the code if you want to try by yourself https://github.com/edgarlcs/rifadisimo

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixes #5743

We accidentally broke Next.js 12 support via #5741 which has an import to `next/headers` that only exists in Next.js 13. This PR wraps the import into a conditional to prevent the error from happening in Next.js 12 apps.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by mmartinsoliv — APPROVED** [review]

File: packages/next-auth/src/next/index.ts [hunk 1]
```diff
@@ -121,18 +120,25 @@ export async function unstable_getServerSession(
...
+        cookies()
+          .getAll()
+          .map((c) => [c.name, c.value])
+      ),
+    }
+    res = { getHeader() {}, setCookie() {}, setHeader() {} }
+  } else {
+    req = args[0]
+    res = args[1]
+    options = args[2]
```
Comment (samuelsd1) [inline packages/next-auth/src/next/index.ts:140]: Maybe it is worth to rewrite as
```js
[req, res, options] = args
```
for better readability?

**Review by ThangHuuVu — APPROVED** [review]
Tested the experimental, LGTM 🚢

File: packages/next-auth/src/next/index.ts (hunk 1 above)
Comment (balazsorban44) [reply packages/next-auth/src/next/index.ts:140]: Syntactical preference. This is internal code anyway, but thanks for the suggestion. :+1:

Would actually be formatted to `;[req, res, options] = args` via Prettier, which I like less. :sweat_smile:

**Comment by dominik-myszkowski** [comment]
Still the same error on 4.18.7
