### PR TITLE
fix(providers): send `client_id` and `client_secret` in body for Instagram Provider

### LINKED ISSUE #3564: Authorization with Instagram fails
### Description 🐜

I try to use the `InstagramProvider`. After successfully signing in and redirecting back to the app, `next-auth` throws the `CALLBACK_OAUTH_ERROR` error. I guess it is from a callback function. The documentation addresses this:

> This can occur during the handling of the callback if the code_verifier cookie was not found or an invalid state was returned from the OAuth provider.

So, this must be an error inside the source code of `next-auth`? Or, am I doing something wrong?

Error message: **"checks.state argument is missing"**

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

My config:
```ts
InstagramProvider({
  clientId: process.env.INSTAGRAM_CLIENT_ID!, 
  clientSecret: process.env.INSTAGRAM_CLIENT_SECRET!,
}),
```

The error is thrown before the `signIn` event is called. After this `next-auth` redirects to `https://f6cf-2a02-587-4c5a-47c6-9917-47c5-aa60-eb3f.ngrok.io/api/auth/signin?error=OAuthCallback#_`

### Screenshots / Logs 📽

_No response_

### Environment 🖥

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
    Memory: 1.13 GB / 5.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.22000.120

### PR DESCRIPTION
**Pull request by iketiunn**
## ☕️ Reasoning

Found that Instagram only accepts client_id and client_secret in the post body. 

Although  https://github.com/nextauthjs/next-auth/pull/3381 can fix it too.
But I think the client meta options are a more clean way to fix it.

refs: 
- https://developers.facebook.com/docs/instagram-basic-display-api/getting-started
- https://github.com/panva/node-openid-client/blob/main/docs/README.md#client-authentication-methods

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Fixes: https://github.com/nextauthjs/next-auth/issues/3564

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

File: packages/next-auth/src/providers/instagram.js [hunk 1]
```diff
@@ -35,6 +35,9 @@ export default function Instagram(options) {
     token: "https://api.instagram.com/oauth/access_token",
     userinfo:
       "https://graph.instagram.com/me?fields=id,username,account_type,name",
+    client: {
+      token_endpoint_auth_method: 'client_secret_post',
```
Comment (balazsorban44) [inline packages/next-auth/src/providers/instagram.js:39]: Thanks! That was my assumption as well in https://github.com/nextauthjs/next-auth/pull/3381#discussion_r775294734

**Review by balazsorban44 — APPROVED** [review]
