### PR TITLE
fix(next-auth): improve typing for using Dynamic Route Segments with auth()

### LINKED ISSUE #9344: How to implement Dynamic Route Segments with Auth Beta
### What is the improvement or update you wish to see?

I can't find how to implement Dynamic routes with the latest beta of authjs

### Is there any context that might help us understand?

with auth handlers it only accept reqeust as params

```
export const GET = auth(async (req) => {
  const session = req.auth;
  if (!session) {
    return Response.json({ error: 'Unauthorized' });
  }
});
```

With next handlers

`app/api/[slug]/route.ts`

```
export async function GET(
  request: Request,
  { params }: { params: { slug: string } }
) {
  const slug = params.slug // 'a', 'b', or 'c'
}
```

### Does the docs page already exist? Please link to it.

_No response_

### PR DESCRIPTION
**Pull request by ethernet8023**
## ☕️ Reasoning
all the plumbing to pass context is already in place,
but the typescript definition doesn't allow `context` to be passed.
this allows dynamic route segments to be used in auth-wrapped api routes without hacky typescript `as any` overrides.
    

this simply adds the typescript typings that reflect what's already being done under the hood.
## 🧢 Checklist

- [x] Documentation (behavior hasn't changed, this is already expected behavior, as seen by confusion in the above issue)
- [x] Tests (behavior hasn't changed)
- [x] Ready to be merged (in my opinion, yes. i'm already using this patch locally and it works great.)

## 🎫 Affected issues
Fixes: https://github.com/nextauthjs/next-auth/issues/9344

### CODE REVIEW

File: packages/next-auth/src/index.tsx [hunk 1]
```diff
@@ -233,7 +233,7 @@ export interface NextAuthResult {
     ((...args: []) => Promise<Session | null>) &
     ((...args: [GetServerSidePropsContext]) => Promise<Session | null>) &
     ((
-      ...args: [(req: NextAuthRequest) => ReturnType<AppRouteHandlerFn>]
+      ...args: [(req: NextAuthRequest, ctx: AppRouteHandlerFnContext) => ReturnType<AppRouteHandlerFn>]
```
Comment (ThangHuuVu) [inline packages/next-auth/src/index.tsx:236]:
```suggestion
      ...args: [(..._args: Parameters<AppRouteHandlerFn>) => ReturnType<AppRouteHandlerFn>]
```
Then no need to export the `AppRouteHandlerFnContext` type

**Review by ThangHuuVu — CHANGES_REQUESTED** [review]
Thanks! I left a suggestion

**Comment by ThangHuuVu** [comment]
Ref: Next.js doc link for [Dynamic Route Segments](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#dynamic-route-segments)

File: packages/next-auth/src/index.tsx (hunk 1 above)
Comment (arilotter) [reply packages/next-auth/src/index.tsx:236]: That won't work, because the AppRouteHandlerFn takes a `NextRequest`, not a `NextAuthRequest`, so the `.auth` param won't be available:
https://github.com/nextauthjs/next-auth/blob/5c3cc2e9facd0ace1da4aac64cacd8c726a837ee/packages/next-auth/src/lib/types.ts#L14

Comment (ThangHuuVu) [reply packages/next-auth/src/index.tsx:236]: I see, then this is fine, resolving.

**Review by ThangHuuVu — APPROVED** [review]
